
name: PHPUnit Tests

on:
  push:
    branches:
      - main  # Adjust if your default branch has a different name
  pull_request:
    branches:
      - '*'  # Trigger the workflow on pull requests targeting any branch

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Environment Variables
        run: |
          echo "ROOTPATH=${GITHUB_WORKSPACE}/" >> $GITHUB_ENV
          echo "APPPATH=${GITHUB_WORKSPACE}/app/" >> $GITHUB_ENV

      - name: Setup PHP Environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --no-suggest  # Install PHP dependencies
  
      - name: Make PHPUnit executable
        run: chmod +x vendor/bin/phpunit 
  
      - name: Make bootstrap readable
        run: chmod +r tests/bootstrap.php 
  
      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --configuration phpunit.xml  # Execute PHPUnit tests
  
      - name: Check PHP version and installed extensions
        run: |
            php -v
            php -m  # Optional: List installed PHP modules