name: PHPUnit Tests

on:
  push:
    branches:
      - main  # Adjust if your default branch has a different name
  pull_request:
        branches:
          - '*'  # Trigger the workflow on pull requests targeting any branch
jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - uses: php-actions/composer@v6
      - run: echo "Composer dependencies have been installed"
      - run: vendor/bin/phpunit